const slides = [
  {
    upperText: 'creative',
    color: 'red',
    title: 'Creative Processes',
    image: './images/creative-process.jpg',
    quote: 'This is a special quote and is very meaningful indeed that it will influence people.',
    quoteName: 'Becky from Technical Services',
    quoteImage: './images/becky.jpg',
  },
  {
    upperText: 'roadmap',
    color: 'blue',
    title: 'Roadmap Management',
    image: './images/roadmap-management.jpg',
    quote: "This is another quote that will make people think and they'll want to buy and use our product.",
    quoteName: 'Samantha from Sales Coordination',
    quoteImage: './images/samantha.jpg',
  },
  {
    upperText: 'content',
    color: 'yellow',
    title: 'Content Calendar',
    image: './images/content-calendar.jpg',
    quote: "I've never been more productive at work than when my company started using this software!",
    quoteName: 'John with State Farm',
    quoteImage: './images/john.jpg',
  },
  {
    upperText: 'HR',
    color: 'purple',
    title: 'HR Management',
    image: './images/hr-management.jpg',
    quote: "Never thought we'd be able to use this software for HR, but since we started I can't think of using anything else!",
    quoteName: 'Jeremy',
    quoteImage: './images/jeremy.jpg',
  },
  {
    upperText: 'work',
    color: 'green',
    title: 'Project Management',
    image: './images/project-management.jpg',
    quote: "I always know where I'm at on my various projects and can easily check in with others to see how their projects are going.",
    quoteName: 'Dani with Cricut',
    quoteImage: './images/dani.jpg',
  },
  {
    upperText: 'team',
    color: 'red',
    title: 'Team Tasks',
    image: './images/team-tasks.jpg',
    quote: 'It can do so many things that it can be tailored to each and every team.',
    quoteName: 'Brixton with Adobe',
    quoteImage: './images/brixton.jpg',
  },
  {
    upperText: 'orders',
    color: 'cyan',
    title: 'Orders',
    image: './images/orders.jpg',
    quote: 'The map view makes it easy to track all of our shipments. This software really is a one-stop shop!',
    quoteName: 'Colton with Minamol',
    quoteImage: './images/colton.jpg',
  },
  {
    upperText: 'sales',
    color: 'orange',
    title: 'Sales Pipeline',
    image: './images/sales-pipeline.jpg',
    quote: 'Our sales numbers have increased 25% since we started using this software. It really helps us follow up on leads.',
    quoteName: 'Jessica with Wavetronix',
    quoteImage: './images/jessica.jpg',
  },
  {
    upperText: 'sprints',
    color: 'blue',
    title: 'Agile Sprints',
    image: './images/agile-sprints.jpg',
    quote: 'When we need something done quickly this is the first place I go to set up assignments.',
    quoteName: 'Sarah with Domo',
    quoteImage: './images/sarah.jpg',
  },
];

export default slides;
